### ISSUE TITLE
file.content is always undefined

### ISSUE THREAD

**Issue by Almoullim** [keroxp/servest#125]
```typescript
import { createApp, contentTypeFilter } from 'https://servestjs.org/@v1.1.0/mod.ts'

const app = createApp()

app.post('/storage/files', contentTypeFilter('multipart/form-data'), async (req) => {
  const bodyForm = await req.formData()
  const file = bodyForm.file('file')

  await bodyForm.removeAll()
  return req.respond({
    status: 200,
    headers: new Headers({ 'content-type': 'application/json' }),
    body: JSON.stringify({
      type: file?.type,
      filename: file?.filename,
      size: file?.size,
    }),
  })
})

app.listen({ port: 8000 })
```

**Comment by keroxp** [comment]
@Almoullim `bodyForm.removeAll()` removes all temporal multipart files stored in fs. In your code, they will have been gone on responding.  So you have to call it after responding. See https://servestjs.org/reading-body

**Comment by Almoullim** [comment]
@keroxp I've tried what you suggested, even completely removing `bodyForm.removeAll()`, still is `undefined`

**Comment by keroxp** [comment]
@Almoullim See https://doc.deno.land/https/deno.land/std/mime/multipart.ts. file.content won't be set if sent file is bigger than max memory size. File data is saved in file located at file.tempfile.

**Comment by Almoullim** [comment]
@keroxp As per the link you sent me, the max memory size by default is 10MB, my file size was 40KB. 

I no longer need to use this, so I will close this issue. You mary reopen if you wish to further investigate but I won't be participating. Thank you.
