### ISSUE TITLE
Help: Stream Large Files

### ISSUE THREAD

**Issue by sspilleman** [keroxp/servest#128]
Hi,

This is a help question. Do you have any example for me how I can stream a large file (mp4) to the browser?
I only see bad examples where people load the file in-memory, which obviously breaks when the file is very large, and It's a terrible practice of course.

Thank you so much!

Sander

**Comment by keroxp** [comment]
@sspilleman Thanks for using servest!

> stream a large file (mp4) to the browser?

Do you talk about simple video tag usage?
`serveStatic` middleware may help you (https://servestjs.org/use-serve-static) 

Or just opening file and pass it to `req.respond()`

```ts
const file = await Deno.open("video.mp4")
try {
  await req.respond({status: 200, body: file})
} finally {
  file.close();
}
```

**Comment by hoangpq** [comment]
@keroxp I think @sspilleman want something like `fs.createReadStream` and stream to browser like

```javascript
var positions = range.replace(/bytes=/, "").split("-");
var start = parseInt(positions[0], 10);
var total = stats.size;
var end = positions[1] ? parseInt(positions[1], 10) : total - 1;
var chunksize = (end - start) + 1;

res.writeHead(206, {
  "Content-Range": "bytes " + start + "-" + end + "/" + total,
  "Accept-Ranges": "bytes",
  "Content-Length": chunksize,
  "Content-Type": "video/mp4"
});
```

**Comment by sspilleman** [comment]
Correct! Ok, will have to wait then!
