### ISSUE TITLE
renderToString is not typed, gives squiggles in VSCode

### ISSUE THREAD

**Issue by Ciantic** [keroxp/servest#133]
![image](https://user-images.githubusercontent.com/64731/85206684-59845880-b32c-11ea-971b-10b339e789ed.png)

Everything else seems to work, it even starts, but that renderToString gives red squiggles as if it was `any`.

Deno 1.1.0
Denoland/deno extension 1.25.0

**Comment by yoshixmk** [comment]
Me too.
As an aside, I tried the other method third-party module [deno_types](https://github.com/Soremwar/deno_types/issues/5), but an error occurred and it did not work.

**Comment by keroxp** [comment]
@Ciantic  Hmm... latest `react-dom-server` may have breaking change? Could you try to remove deno-types annotation for react-domserver and check it works?

**Comment by Ciantic** [comment]
@keroxp sure. Btw this is the example you give in the README.

![image](https://user-images.githubusercontent.com/64731/85232595-bce3b880-b408-11ea-898b-92314ed37723.png)

It doesn't seem to work now at all for some reason.

**Comment by keroxp** [comment]
@Ciantic Yeah it is issue of deno-vscode. So no way to fix it by us. Would you close the issue?
