### ISSUE TITLE
[Feature Request] per-route middlewares

### ISSUE THREAD

**Issue by ibraheem-ghazi** [keroxp/servest#139]
I'm looking for per-route middlewares but couldn't find any easy way to implement it.

suggestion: `router.get('/', (req)=>{}).use([ /* array of middlewares functions */ ])`;

**Comment by keroxp** [comment]
@ibraheem-ghazi  

>per-route middlewares

What do you mean?  Each route method accept multiple handlers(middleware), isn't it enough?

```js
router.get("/", middleware1, middleware2, req => {})
```

**Comment by ibraheem-ghazi** [comment]
hmmm, didn't found this in documentation. 😅
thanks for mentioning this.
