### ISSUE TITLE
Looking for logo designs

### ISSUE THREAD

**Issue by keroxp** [keroxp/servest#47]
- We are looking for the brand logo of  servest.
- If you are interested in this, please add comment to this issue.

## Concept

- Canonical name of project is `Servest`, capitalized.
- Alternative name is `Servest.js`, capitalized and `.js` added.

## Meaning

- `Servest` is a coinage that means `Server + Harvest`. We aim for to be a rich harvest in http server development in JavaScript. 

## Motif and Colors

- Official motif is a ear of rice plant.（稲穂）
- Apple's emoji of rice plant is a good example:
![favicon](https://user-images.githubusercontent.com/927286/67199197-a16c7c00-f43b-11e9-8969-0b4992ca1375.png)
- Primary color is Yellow or gold. Secondary is green.

## Copyrights and License

- All rights will belong to `(c) Servest Authors`
- All artifacts will be distributed under guidelines like: https://github.com/logos
- Your name will be credited to README.md and https://servestjs.org

## Fee

- No fee will be paid. Your contributions are treated same as other contributors (Pull-Request, Issues...).

**Comment by uetchy** [comment]
I just came across with this issue and was thinking about it. So here is my idea sketch for Servest logo:
![Artboard Copy 3](https://user-images.githubusercontent.com/431808/67583865-68a80c00-f787-11e9-989a-4bb25b930e63.png)

It illustrates a simplified tip part of rice plants along circular shape. I gave up adding a greeny motif because it doesn't match well with this figure.
What do you think?

Font: Acrom Bold

**Comment by keroxp** [comment]
@uetchy Thank you very much for your idea sketches! Great👍

I'm very glad you attempt to contribute this project, sincerely. Welcome.

At a glance, I feel something below:

- Circular shape is good. I imagined like that.
- `.js` typography is cool.
- Shape of rice plant may be too simplified and abstracted, IMO
  - I couldn't imagine the logo means ear of rice plant. 
  - It may be good to think that rice plant is composed of three different colors and shapes:
     - Leaves（葉）
     - Stalk（茎）
     - Fruits（実）
  - Also would you try to let colors (Yellow and Green) coexist again?
  - I felt impression of circularness strongly than what shape means. Is sun? Is moon? ...
  - Also emptiness for center of circle.
- Color looks orange rather than yellow
  - Would you change gradient hue value more into yellow side?

How about? Do you have any other questions for your work?

**Comment by uetchy** [comment]
@keroxp Thanks for reviewing my sketch!
I'm seeing it almost requires redesigning it from scratch and unfortunately I cannot take much time to do it atm. any chance to relax requirements? or I suggest keeping the issue open so that others might be interested in designing a logo.

**Comment by keroxp** [comment]
@uetchy If you don't have much time to do now, I recommend you to concentrate on your own work at this time. So would you stop working for the issue for a time? I'm happy you would contribute the project but some progress is needed. I want to move it forward some way. I'm going to stop the recruitment  here and look for it by my own way. Is it OK? Thank you very much!

**Comment by keroxp** [comment]
@uetchy Thank you. If you have a much time to contribute, please give us an idea.
