### ISSUE TITLE
[site] Mobile accesibility

### ISSUE THREAD

**Issue by keroxp** [keroxp/servest#51]
- https//servestjs.org is currently less accessible on mobile device.
- Planning to apply mobile css but delayed...

**Comment by LaggerP** [comment]
Hey! do you want to keep the present design (colors, structure, etc.) or exist any possibility in the future to change it?

**Comment by keroxp** [comment]
@LaggerP About color and structure, there're no plan to change or not. But contents must be kept. I was investigating css framework for site but couldn't find the good one. Most modern css frameworks depend on node/npm😢 I'd like build site with only deno tools as possible. It's still hard.

**Comment by LaggerP** [comment]
😢 and do the web with classic css using grids and flexbox? very hardest work no? and very difficult to maintain in the future...
